### ISSUE TITLE
For the love of god, put a reminder over the purchase button

### ISSUE THREAD

**Issue by ZdrytchX** [cyberofficial/Gaijin-Creators-Extension#1]
I keep forgetting. I've not once selected a content creator to support D:

**Comment by cyberofficial** [comment]
I'll implement that

**Comment by cyberofficial** [comment]
Added a pop up reminder on check out
![opera_JL6yDM9zkR](https://github.com/cyberofficial/Gaijin-Creators-Extension/assets/19499442/276c36de-0da3-48d1-aeaf-362e8c901d63)


Added big header on check out as well.
![opera_jQv4t2znYn](https://github.com/cyberofficial/Gaijin-Creators-Extension/assets/19499442/30fedf21-b9aa-44ba-b65e-311bf7ab9313)

**Comment by ZdrytchX** [comment]
thanks

not sure if something broke but using the extension to select any content creator now leads to a 404 page with an errornous 404 page with the box icon and error message quickly being replaced with "Thank you for supporting: [insert name here]" with their decal above. I tried switching to another chromium based browser (edge) and I'm getting similar results, and this does not provide 3% discount on any in-store non-discounted item.

I tried a random twitch streamer and his hyperlink is suffixed `catalog.php?category=WarThunder&partner=BPA_Jon&partner_val=n6ylk6r4` and confirmed this does work and correctly applies 3% discount on non-discounted items, whereas your equivalent url is just suffixed with the CC's name `BPA_Jon` which returns 404 error with no change to the store.

**Comment by cyberofficial** [comment]
Hello, I do not see the same issue; On latest chrome using the latest extension Ver. 1.0.438
https://github.com/cyberofficial/Gaijin-Creators-Extension/assets/19499442/1d23e007-101f-4f8b-ace8-32c99c1f6c39

Are you able to recreate your issue over video or show the screenshots of the issue?

With the extension installed you should be able to visit [https://store.gaijin.net/BPA_Jon](https://store.gaijin.net/BPA_Jon ) as a url aswell and get the thank you page and if you want to confirm the discount or not.
