### ISSUE TITLE
Suggest A Creator

### ISSUE THREAD

**Issue by Panuch412** [cyberofficial/Gaijin-Creators-Extension#2]
Seek recently got his decal added for the shop discount, I would love to see his discount code in the extension! 
(Link to seek's discount) https://store.gaijin.net/catalog.php?category=WarThunder&partner=Seek&partner_val=7zuxqznm

**Comment by cyberofficial** [comment]
Hi, lists were updated and will be reflected in the chrome and ff store soon after verification.
